on:
  schedule:
    - cron:  '0/15 * * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Oliver Forral's website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://oliverforral.com/'
